<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706104309 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE yield_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, wallet_address VARCHAR(42) NOT NULL, shares VARCHAR(78) NOT NULL, principal_minor_units VARCHAR(78) NOT NULL, yield_received VARCHAR(78) NOT NULL, flow_rate VARCHAR(78) NOT NULL, connected BOOLEAN NOT NULL, paused BOOLEAN NOT NULL, apr_basis_points INT NOT NULL, captured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_yield_snapshot_wallet_captured_at ON yield_snapshot (wallet_address, captured_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE yield_snapshot');
    }
}
