<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260707171008 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'M4 — Tontine domain: tontine_group, tontine_membership, tontine_savings_cycle, tontine_contribution.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tontine_contribution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tx_hash VARCHAR(66) NOT NULL, amount_minor_units VARCHAR(78) NOT NULL, contributed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, group_id INT NOT NULL, membership_id INT NOT NULL, cycle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3A011CE28854154 ON tontine_contribution (tx_hash)');
        $this->addSql('CREATE INDEX IDX_B3A011CEFE54D947 ON tontine_contribution (group_id)');
        $this->addSql('CREATE INDEX IDX_B3A011CE1FB354CD ON tontine_contribution (membership_id)');
        $this->addSql('CREATE INDEX IDX_B3A011CE5EC1162 ON tontine_contribution (cycle_id)');
        $this->addSql('CREATE TABLE tontine_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, contribution_amount_minor_units VARCHAR(78) NOT NULL, periodicity VARCHAR(16) NOT NULL, installments_per_cycle INT NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tontine_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(16) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, group_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D0302B5FE54D947 ON tontine_membership (group_id)');
        $this->addSql('CREATE INDEX IDX_6D0302B5A76ED395 ON tontine_membership (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tontine_membership_group_user ON tontine_membership (group_id, user_id)');
        $this->addSql('CREATE TABLE tontine_savings_cycle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cycle_number INT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(16) NOT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89F3FA78FE54D947 ON tontine_savings_cycle (group_id)');
        $this->addSql('ALTER TABLE tontine_contribution ADD CONSTRAINT FK_B3A011CEFE54D947 FOREIGN KEY (group_id) REFERENCES tontine_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tontine_contribution ADD CONSTRAINT FK_B3A011CE1FB354CD FOREIGN KEY (membership_id) REFERENCES tontine_membership (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tontine_contribution ADD CONSTRAINT FK_B3A011CE5EC1162 FOREIGN KEY (cycle_id) REFERENCES tontine_savings_cycle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tontine_membership ADD CONSTRAINT FK_6D0302B5FE54D947 FOREIGN KEY (group_id) REFERENCES tontine_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tontine_membership ADD CONSTRAINT FK_6D0302B5A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tontine_savings_cycle ADD CONSTRAINT FK_89F3FA78FE54D947 FOREIGN KEY (group_id) REFERENCES tontine_group (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tontine_contribution DROP CONSTRAINT FK_B3A011CEFE54D947');
        $this->addSql('ALTER TABLE tontine_contribution DROP CONSTRAINT FK_B3A011CE1FB354CD');
        $this->addSql('ALTER TABLE tontine_contribution DROP CONSTRAINT FK_B3A011CE5EC1162');
        $this->addSql('ALTER TABLE tontine_membership DROP CONSTRAINT FK_6D0302B5FE54D947');
        $this->addSql('ALTER TABLE tontine_membership DROP CONSTRAINT FK_6D0302B5A76ED395');
        $this->addSql('ALTER TABLE tontine_savings_cycle DROP CONSTRAINT FK_89F3FA78FE54D947');
        $this->addSql('DROP TABLE tontine_contribution');
        $this->addSql('DROP TABLE tontine_group');
        $this->addSql('DROP TABLE tontine_membership');
        $this->addSql('DROP TABLE tontine_savings_cycle');
    }
}
